name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version
        run: TAG="${{github.ref}}"; echo "VERSION=${TAG#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Package
        uses: ./.github/actions/build

      - name: Extract Config Signature
        run: cat src/conf/confparser.h | sed -n 's/^#define .\+_SIGNATURE\W\+\([0-9]*\)/\1/p' > config_signature.txt

      - name: Rename Package File
        run: mv refloat.vescpkg refloat-${{env.VERSION}}.vescpkg

      - name: Install Changelog Generation Dependencies
        run: sudo apt-get install python3-git

      - name: Generate Changelog
        run: python changelog.py > changelog.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{github.ref}}
          name: Refloat ${{env.VERSION}}
          draft: true
          artifacts: "refloat-${{env.VERSION}}.vescpkg,config_signature.txt"
          bodyFile: "changelog.md"
          prerelease: ${{contains(github.ref, '-beta')}}
          allowUpdates: true
